#!/usr/bin/env ruby
# encoding: utf-8


# Crude hack to update the end of the README file with the list of plugins

plugins = File.open(File.expand_path('./plugs.vim')).readlines.map do |line|
  if match = %r{^\A*Plug\s+(?<quote>["'])(?<plug_name>.*?)\k<quote>}.match(line)
    repo, user = match[:plug_name].split('/').reverse
    user ||= "vim-scripts"

    " * [#{repo}](https://github.com/#{user}/#{repo})"
  end
end.compact.sort.join("\n")


File.open("./README.markdown", 'r+') do |readme|
  content = readme.read
  readme.rewind
  readme.write content.sub(/^(## Plugins:).*\Z/ms, "\\1\n\n#{plugins}")
end
