#!/bin/sh

# Generate per-tool keybinding fragments from the single source of truth.
# POSIX-compliant: reads configs/keybindings.sh and writes native fragments
# for tmux, zsh, and Neovim. Idempotent — running twice produces identical
# output.

set -eu

# Resolve the repository root relative to this script (works from any CWD,
# including a git worktree). This script lives in scripts/setup/.
_script_path="$0"
case "${_script_path}" in
/*)
  _script_dir=$(dirname "${_script_path}")
  ;;
*)
  _script_dir=$(cd "$(dirname "${_script_path}")" && pwd)
  ;;
esac
_repo_root=$(cd "${_script_dir}/../.." && pwd)

_src="${_repo_root}/configs/keybindings.sh"
if [ ! -f "${_src}" ]; then
  printf '❌ keybindings source not found at %s\n' "${_src}" >&2
  exit 1
fi

# shellcheck source=/dev/null
. "${_src}"

# --- Notation translators --------------------------------------------------

# tmux understands C-x, M-x, and Space natively, so this is a pass-through.
kb_to_tmux() {
  printf '%s' "$1"
}

# zsh `bindkey` notation: Ctrl -> ^<UPPER>, Meta -> ^[<char>, Space -> ' '.
kb_to_zsh() {
  case "$1" in
  Space)
    printf "' '"
    ;;
  C-?)
    _c=$(printf '%s' "$1" | cut -c3 | tr '[:lower:]' '[:upper:]')
    printf "'^%s'" "${_c}"
    ;;
  M-?)
    _c=$(printf '%s' "$1" | cut -c3)
    printf "'^[%s'" "${_c}"
    ;;
  *)
    printf "'%s'" "$1"
    ;;
  esac
}

# Neovim key form: C-x -> <C-x>, M-x -> <M-x>, Space -> <Space>.
kb_to_nvim() {
  case "$1" in
  Space)
    printf '<Space>'
    ;;
  C-? | M-?)
    printf '<%s>' "$1"
    ;;
  *)
    printf '%s' "$1"
    ;;
  esac
}

# Neovim literal string value (for `let mapleader = "..."`): Space -> a real
# space; everything else passes through (e.g. "," or "\").
kb_to_nvim_literal() {
  case "$1" in
  Space)
    printf ' '
    ;;
  *)
    printf '%s' "$1"
    ;;
  esac
}

_header_hash="# Generated by scripts/setup/generate-keybindings.sh — DO NOT EDIT.
# Source of truth: configs/keybindings.sh"
_header_dquote='" Generated by scripts/setup/generate-keybindings.sh — DO NOT EDIT.
" Source of truth: configs/keybindings.sh'

# --- tmux ------------------------------------------------------------------

_tmux_out="${_repo_root}/configs/terminal/tmux/keybindings.generated.conf"
{
  printf '%s\n\n' "${_header_hash}"
  printf 'set -g prefix %s\n' "$(kb_to_tmux "${KB_TMUX_PREFIX}")"
  # Emit the bindings table. Each line is FLAGS:::KEY:::ACTION.
  printf '%s' "${KB_TMUX_BINDS}" | while IFS= read -r _line || [ -n "${_line}" ]; do
    case "${_line}" in
    '' | '#'*) continue ;;
    esac
    _flags=${_line%%:::*}
    _rest=${_line#*:::}
    _key=${_rest%%:::*}
    _action=${_rest#*:::}
    if [ "${_flags}" = "-" ]; then
      printf 'bind %s %s\n' "$(kb_to_tmux "${_key}")" "${_action}"
    else
      printf 'bind %s %s %s\n' "${_flags}" "$(kb_to_tmux "${_key}")" "${_action}"
    fi
  done
} >"${_tmux_out}"
printf '✅ wrote %s\n' "${_tmux_out}"

# --- Neovim ----------------------------------------------------------------

_nvim_out="${_repo_root}/configs/editor/nvim/key_mappings/keybindings.generated.vim"
{
  printf '%s\n\n' "${_header_dquote}"
  printf 'let mapleader = "%s"\n' "$(kb_to_nvim_literal "${KB_NVIM_LEADER}")"
} >"${_nvim_out}"
printf '✅ wrote %s\n' "${_nvim_out}"

# --- zsh -------------------------------------------------------------------

_zsh_out="${_repo_root}/configs/shell/zsh/keybindings.generated.zsh"
{
  printf '%s\n\n' "${_header_hash}"
  printf 'bindkey %s backward-kill-line\n' "$(kb_to_zsh "${KB_ZSH_KILL_LINE}")"
} >"${_zsh_out}"
printf '✅ wrote %s\n' "${_zsh_out}"
