
# General environment variables

export ENABLE_WASM=
export EDITOR="nvim"
export VISUAL="nvim" 
export SHELL='/usr/bin/zsh'

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# Language and locale settings

export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

export PATH=$HOME/.local/bin:$PATH

# Oh-My-Zsh settings

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="ys"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
export PYTHON_CONFIGURE_OPTS="--enable-shared"

export PATH=$HOME/.cargo/bin:$PATH

# Java 
export PATH=/usr/local/jdk-1.8.0/bin:$PATH
export JAVA_HOME=/usr/local/jdk-1.8.0/

# Jump in directories
source ~/z.sh

# General Fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=$PATH:$HOME/.tfenv/bin

# Volta is a hassle-free way to manage 
# your JavaScript command-line tools.
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/plugins/golang/set-env.zsh"
eval "$(~/.rbenv/bin/rbenv init - zsh)"

### Added by Zinit's installer

if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

# zsh-fzf-history-search
zinit ice lucid wait'0'
zinit light joshskidmore/zsh-fzf-history-search

plugins=(
 man
 git github
 systemd
 tmux tmuxinator
 ruby gem
 rust
 golang
 aws
 terraform
 zsh-fzf-history-search
 docker docker-compose
 direnv
 kubectl helm
 vault
 node
 python pip poetry pyenv pylint
 torrent asdf gcloud ag volta)

# Check if the .zsh.local folder exists
if [[ -d "$HOME/.zsh.local" ]]; then
  # Source all .zsh files in the .zsh.local folder
  for file in "$HOME/.zsh.local"/*.zsh; do
    if [[ -f "$file" ]]; then
      source "$file"
    fi
  done
fi

# Utils & aliases

function reload {
  source ~/.zshrc
}

alias c=clear
alias tx=tmuxinator
alias running_services='systemctl list-units  --type=service  --state=running'
alias update-nvim-stable='asdf uninstall neovim stable && asdf install neovim stable'
alias update-nvim-nightly='asdf uninstall neovim nightly && asdf install neovim nightly'
alias update-nvim-master='asdf uninstall neovim ref:master && asdf install neovim ref:master'

# source 

source $ZSH/oh-my-zsh.sh
