[tools]
awscli = "latest"
bat = "latest"
deno = "latest"
gh = "latest"
glab = "latest"
ruby = "latest"
terraform-docs = "latest"
terraformer = "latest"
vault = "latest"
terragrunt = "latest"
terraform = "latest"
rust = "latest"
k9s = "latest"
kubectl = "latest"
crystal = "latest"
tfstate-lookup = "latest"
ctop = "latest"
direnv = "latest"
